spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
  jpa:   
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect   