spring:
  datasource:
    url: jdbc:mysql://localhost/db_springboot?useSSL=false
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB     
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
server:
  port: 8080   