spring:
  datasource:
    url: jdbc:mysql://localhost/db_springboot_backend?useSSL=false
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org:
      hiberntae:
        SQL: debug