spring:
  datasource:
    url: jdbc:mysql://localhost/db_springboot?useSSL=false
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop  
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    