INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (1, 'Andres', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28');
INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (2, 'John ', 'Doe', 'john.doe@gmail.com', '2017-08-28');
INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (3, 'Andres2', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28');
INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (4, 'John2 ', 'Doe', 'john.doe@gmail.com', '2017-08-28');
INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (5, 'Andres3', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28');
INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (6, 'John3 ', 'Doe', 'john.doe@gmail.com', '2017-08-28');
INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (7, 'Andres4', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28');
INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (8, 'John4 ', 'Doe', 'john.doe@gmail.com', '2017-08-28');
INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (9, 'Andres5', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28');
INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (10, 'John5 ', 'Doe', 'john.doe@gmail.com', '2017-08-28');
INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (11, 'Andres6', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28');
INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (12, 'John6 ', 'Doe', 'john.doe@gmail.com', '2017-08-28');
INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (13, 'Andres7', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28');
INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (14, 'John7 ', 'Doe', 'john.doe@gmail.com', '2017-08-28');
INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (15, 'Andres8', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28');
INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (16, 'John8 ', 'Doe', 'john.doe@gmail.com', '2017-08-28');
INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (17, 'Andres9', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28');
INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (18, 'John9 ', 'Doe', 'john.doe@gmail.com', '2017-08-28');
INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (19, 'Andres0', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28');
INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (20, 'John0 ', 'Doe', 'john.doe@gmail.com', '2017-08-28');
INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (21, 'Andres11', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28');
INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (22, 'John11', 'Doe', 'john.doe@gmail.com', '2017-08-28');
--INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (23, 'Andres12', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28');
--INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (24, 'John12', 'Doe', 'john.doe@gmail.com', '2017-08-28');
--INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (25, 'Andres13', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28');
--INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (26, 'John13 ', 'Doe', 'john.doe@gmail.com', '2017-08-28');
--INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (27, 'Andres14', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28');
--INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (28, 'John14', 'Doe', 'john.doe@gmail.com', '2017-08-28');
--INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (29, 'Andres15', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28');
--INSERT INTO clientes (id, nombre, apellido, email, create_at) VALUES (30, 'John15', 'Doe', 'john.doe@gmail.com', '2017-08-28');
