INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres2', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John2 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres3', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John3 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres4', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John4 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres5', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John5 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres6', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John6 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres7', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John7 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres8', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('John8 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres9', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('John9 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres0', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John0 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres11', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John11', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres2', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John2 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres3', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John3 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres4', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John4 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres5', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John5 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres6', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John6 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres7', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John7 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres8', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('John8 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres9', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('John9 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres0', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John0 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres11', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John11', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres2', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John2 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres3', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John3 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres4', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John4 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres5', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John5 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres6', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John6 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres7', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John7 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres8', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('John8 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres9', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('John9 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres0', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John0 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres11', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John11', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres2', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John2 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres3', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John3 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');

--INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES (23, 'Andres12', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
--INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES (24, 'John12', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
--INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES (25, 'Andres13', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
--INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES (26, 'John13 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
--INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES (27, 'Andres14', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
--INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES (28, 'John14', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
--INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES (29, 'Andres15', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
--INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES (30, 'John15', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
