INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres2', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John2 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres3', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John3 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres4', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John4 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres5', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John5 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres6', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John6 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres7', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John7 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres8', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('John8 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres9', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('John9 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres0', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John0 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres11', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John11', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres2', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John2 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres3', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John3 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres4', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John4 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres5', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John5 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres6', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John6 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres7', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John7 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres8', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('John8 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres9', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('John9 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres0', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John0 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres11', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John11', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres2', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John2 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres3', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John3 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres4', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John4 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres5', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John5 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres6', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John6 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres7', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John7 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres8', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('John8 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres9', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('John9 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres0', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John0 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres11', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John11', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres2', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John2 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'Andres3', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-28','');
INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ( 'John3 ', 'Doe', 'john.doe@gmail.com', '2017-08-28','');

/* Populate tabla productos */
INSERT INTO productos (nombre, precio, create_at) VALUES('Panasonic Pantalla LCD', 259990, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES('Sony Camara digital DSC-W320B', 123490, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES('Apple iPod shuffle', 1499990, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES('Sony Notebook Z110', 37990, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES('Hewlett Packard Multifuncional F2280', 69990, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES('Bianchi Bicicleta Aro 26', 69990, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES('Mica Comoda 5 Cajones', 299990, NOW());

/* Creamos algunas facturas */
INSERT INTO facturas (descripcion, observacion, cliente_id, create_at) VALUES('Factura equipos de oficina', null, 1, NOW());
INSERT INTO facturas_items (cantidad, factura_id, producto_id) VALUES(1, 1, 1);
INSERT INTO facturas_items (cantidad, factura_id, producto_id) VALUES(2, 1, 4);
INSERT INTO facturas_items (cantidad, factura_id, producto_id) VALUES(1, 1, 5);
INSERT INTO facturas_items (cantidad, factura_id, producto_id) VALUES(1, 1, 7);

INSERT INTO facturas (descripcion, observacion, cliente_id, create_at) VALUES('Factura Bicicleta', 'Alguna nota importante!', 1, NOW());
INSERT INTO facturas_items (cantidad, factura_id, producto_id) VALUES(3, 2, 6);

/* Creamos algunos usuarios con sus roles */
INSERT INTO users (username, password, enabled) VALUES ('andres','$2a$10$8ZRAEwOacrV.9Qq2iDGLpu9g5k.MBL0K9Vm/zSRAjH7a3s5e2oV/a',1);
INSERT INTO users (username, password, enabled) VALUES ('admin','$2a$10$K.VFN6PaUZUfP/jHXxlVvu7hnK1KGM0kPePnsr0LZ5/OUhRvkeJC2',1);

INSERT INTO authorities(user_id, authority) VALUES (1, 'ROLE_USER');
INSERT INTO authorities(user_id, authority) VALUES (2, 'ROLE_ADMIN');
INSERT INTO authorities(user_id, authority) VALUES (2, 'ROLE_USER');