spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:   
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        use_sql_comments: true
  thymeleaf:
    cache: false      
